name: Strict View Data Gem

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  gem:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.2', '3.4']
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: 単体テスト
        run: bundle exec rake
      - name: Gemをビルド
        run: gem build strict_view_data.gemspec
